"""Reviewed calculator-specific documentation used by pythonultra_docs.py."""

OVERVIEWS = {
'builtins': 'Core Python types, functions and exceptions. Available without an import. This is MicroPython, so optional CPython features may be absent.',
'sys': 'Interpreter identity, imports and program arguments. version begins with Python compatibility 3.4.0; implementation.version identifies MicroPython 1.25.0-preview. path controls imports; argv holds script arguments.',
'micropython': 'MicroPython compiler and memory controls. Prefer ordinary Python until memory measurements justify an optimization.',
'gc': 'Garbage collection and heap measurements. Memory is limited on the calculator; free unused images and arrays before collecting.',
'math': 'Real-valued mathematics using double-precision floats in this port. Trigonometric arguments are radians.',
'cmath': 'Complex-valued mathematics. Functions accept real or complex inputs; angles are radians.',
'array': 'Compact homogeneous numeric arrays. Type codes select element representation; array storage differs from the pure-Python numpy.ndarray container.',
'collections': 'Small collection helpers. Only the exported classes listed below are part of this build.',
'io': 'In-memory text/binary streams and native calculator files. Close files, use binary mode for archives and images, and check errors. Native seek/tell were corrected in run130.',
'json': 'Read and write JSON data using strings or streams. Suitable for small settings/data files; avoid loading files larger than the calculator heap.',
'struct': 'Pack/unpack binary values. Use explicit < or > byte order for portable data; the calculator target is big-endian.',
'random': 'Pseudorandom values for games and sampling. Not a cryptographic random source; seed explicitly for reproducible examples.',
'binascii': 'Binary/ASCII conversions and CRC32 checksums. CRC32 detects accidental corruption, not authenticity.',
'errno': 'Symbolic OS error numbers. Compare error.args[0] against these names when handling OSError.',
'deflate': 'Streaming raw DEFLATE, zlib and gzip compression/decompression. Compression is enabled in PythonUltra. Close the compressor to finish the stream. Large-file speed is under repair.',
'time': 'Delays and tick counters. Current time() is RTC seconds since midnight, not a Unix timestamp. Adjustable date/time is still pending. Use ticks_diff for elapsed intervals. monotonic currently has nonstandard nanosecond-valued units.',
'gint': 'Native fx-CG50 drawing and keyboard interface. Screen: 396 x 224. Colors are RGB565 integers. Every import can invoke the builtin initializer, clearing VRAM to white and resetting the font. Import before drawing, outside animation loops. Draw into VRAM, then call dupdate(). Keyboard events have type/key/time/mod/shift/alpha fields.',
'os': 'Calculator filesystem with a virtual current directory. This is a limited API, not POSIX or desktop os. Missing or unsupported stat timestamp fields must not be treated as valid dates.',
'ctypes': 'Restricted scalar conversions and bounds-checked managed buffers. There are no arbitrary pointers, shared-library loading, Structures or unrestricted native calls. c_int/c_float return ordinary Python values, not .value wrappers.',
'checksum': 'SHA-256 and SHA-1 file digests. Reads calculator files; errors propagate. SHA-1 is provided for compatibility, not collision-resistant security.',
'casioplot': 'Casio-style pixel and text drawing compatibility using the gint display. Call show_screen() after drawing.',
'kandinsky': 'NumWorks-style color/pixel/text/rectangle helpers on the fx-CG50. Coordinate/color behavior follows this port; not all NumWorks APIs exist.',
'ion': 'NumWorks-style key-state compatibility. Use the KEY_* constants from this module with keydown().',
'pygame': 'Compact Pygame-compatible layer. One 396 x 224 display, RGB565 pixels, keyboard controls. No audio, real mouse, SDL windowing, per-pixel alpha or general desktop image codecs. BMP loading is bounded to 56 x 56. RGB565 screen blits with set_colorkey now use one native draw call, with source/destination clipping and no transparency cache. Transforms retain the color key. Host pixel tests pass; smooth movement still needs hardware confirmation. Repaint the background and all sprites each frame; Group.draw does not erase old positions.',
'pygame.math': 'Vector2 and Vector3 helpers. Indexing, iteration, vector arithmetic and scalar multiplication/division are supported. Vector2 angles are degrees; normalize() on a zero vector raises ValueError.',
'numpy': 'Pure-Python, calculator-sized array/matrix subset. Small arrays only; not compiled desktop NumPy. ndarray * is elementwise; matrix * uses matrix multiplication. Inverse is matrix.I/getI(); there is no numpy.linalg module. Broadcasting and axis arguments are limited to the implementation below.',
'py3d': 'Compact software 3D engine. Camera looks along +Z; matrices are row-major 4 x 4 tuples. Painter sorting, back-face culling, optional lighting and native filled triangles. No depth buffer or near-plane triangle clipping; triangles crossing the near plane are skipped.',
'pythonultra': 'On-calculator Catalog, modal menus, theme/border and build information. Catalog entries are insertion aids; they are not a complete implementation inventory.',
'pyeditor': 'Calculator text editor: safe New/Open/Save, Find, Run, selection and multiline paste. File limit 65,536 bytes / 2,048 lines. F6 Sym opens symbols; SHIFT+VARS opens Style. In alpha mode SHIFT reverses case for the next character; the a/A indicator reflects it. Repeated arrows/delete are coalesced and released keys stop repeating. Dark canvases and bars are black. Hardware confirmation of these corrections is pending. API methods below are available for customization; typical programs only use open_file or new_file.',
'pyfiles': 'Calculator file browser, previews, editor launcher, clipboard, permissions and ZIP actions. Typical entry point: browse(). The current text viewer clips long lines; this is an active fix.',
'pyperm': 'PythonUltra-managed virtual rwx permissions. These checks apply to cooperating PythonUltra tools, not native OS-wide file protection. Permission database changes can affect editing and file operations.',
'pyterm': 'Small Linux-like command layer with aliases, history and an RC file. dispatch() is the native shell bridge, not a general subprocess API. startup_view() honors RC startup=terminal/files, default files.',
'zipfile': 'Standard stored/DEFLATE ZIP files with CRC checking and cleanup of failed extraction. No ZIP64, encryption, multidisk or desktop ZipFile class. Existing archive/destination files are preserved rather than overwritten. Large-file compression responsiveness is an active fix.',
}

EXAMPLES = {
'builtins': 'values = [3, 1, 2]\nprint(sorted(values), sum(values))\nfor index, value in enumerate(values):\n    print(index, value)',
'sys': 'import sys\nprint(sys.implementation)\nprint(sys.implementation.version)\nprint(sys.path, sys.argv)',
'micropython': 'import micropython\nprint(micropython.const(12))',
'gc': 'import gc\ngc.collect()\nprint(gc.mem_free(), gc.mem_alloc())',
'math': 'import math\nprint(math.sqrt(25), math.sin(math.pi / 2))',
'cmath': 'import cmath\nprint(cmath.sqrt(-1), cmath.phase(1j))',
'array': 'from array import array\na = array("h", [1, 2, 3])\na.append(4)\nprint(a[0], len(a))',
'collections': 'from collections import namedtuple\nPoint = namedtuple("Point", ("x", "y"))\np = Point(3, 4)\nprint(p.x, p.y)',
'io': 'import io\nf = io.BytesIO()\nf.write(b"hello")\nf.seek(0)\nprint(f.read())\nf.close()',
'json': 'import json\ntext = json.dumps({"score": 12, "alive": True})\nprint(text)\nprint(json.loads(text)["score"])',
'struct': 'import struct\nraw = struct.pack("<H", 513)\nprint(raw, struct.unpack("<H", raw))',
'random': 'import random\nrandom.seed(42)\nprint(random.randint(1, 6), random.choice(["red", "blue"]))',
'binascii': 'import binascii\nprint(binascii.hexlify(b"AB"))\nprint(binascii.crc32(b"hello"))',
'errno': 'import errno\ntry:\n    open("missing-example.txt", "r")\nexcept OSError as error:\n    print(error.args[0] == errno.ENOENT)',
'deflate': 'import io, deflate\nbuf = io.BytesIO()\nwith deflate.DeflateIO(buf, deflate.ZLIB) as compressor:\n    compressor.write(b"hello hello hello")\nbuf.seek(0)\nwith deflate.DeflateIO(buf, deflate.ZLIB) as reader:\n    print(reader.read())',
'time': 'import time\nstart = time.ticks_ms()\ntime.sleep_ms(20)\nprint(time.ticks_diff(time.ticks_ms(), start))',
'gint': 'import gint\ngint.dclear(gint.C_BLACK)\ngint.dtext(4, 4, gint.C_WHITE, "PythonUltra")\ngint.dline(0, 30, 100, 70, gint.C_RED)\ngint.dupdate()\ngint.getkey()',
'os': 'import os\nprint(os.getcwd())\nfor name in os.listdir("."):\n    print(name)',
'ctypes': 'import ctypes\nbuf = ctypes.buffer(8)\nctypes.write_u8(buf, 0, 42)\nprint(ctypes.read_u8(buf, 0))\nprint(ctypes.call("sqrt", 25))',
'checksum': 'import checksum\n# Replace demo.py with an existing readable file.\nprint(checksum.sha256_file("demo.py"))',
'casioplot': 'import casioplot\ncasioplot.clear_screen()\ncasioplot.set_pixel(10, 10, (255, 0, 0))\ncasioplot.draw_string(2, 2, "Hello", (0, 0, 0), "small")\ncasioplot.show_screen()',
'kandinsky': 'import kandinsky\nkandinsky.fill_rect(0, 0, 40, 30, (255, 0, 0))\nkandinsky.draw_string("Hi", 2, 2)\nimport gint\ngint.dupdate()',
'ion': 'import ion\nprint(ion.keydown(ion.KEY_LEFT))',
'pygame': 'import pygame\npygame.init()\nscreen = pygame.display.set_mode((396, 224))\nclock = pygame.time.Clock()\nx = 10\nfor frame in range(120):\n    pygame.event.get()\n    screen.fill((0, 0, 0))\n    pygame.draw.rect(screen, (255, 80, 20), (x, 70, 16, 16))\n    pygame.display.flip()\n    x = (x + 2) % 380\n    clock.tick(30)\npygame.quit()',
'pygame.math': 'from pygame.math import Vector2, Vector3\nv = Vector2(3, 4)\nprint(v.length(), v.normalize())\nprint(Vector3(1, 0, 0).cross(Vector3(0, 1, 0)))',
'numpy': 'import numpy as np\na = np.matrix([[1, 2], [3, 4]])\nprint(a.T.tolist())\nprint(a.I.tolist())\nprint((a * a.I).tolist())\nprint(np.cross([1, 0, 0], [0, 1, 0]))',
'py3d': 'from py3d import vec3, dot, cross, translation, transform\na = vec3(1, 0, 0)\nb = vec3(0, 1, 0)\nprint(dot(a, b), cross(a, b))\nprint(transform(a, translation(0, 0, 5)))',
'pythonultra': 'import pythonultra\nprint(pythonultra.modules())\npythonultra.catalog("numpy")\nprint(pythonultra.catalog_text("numpy", "array"))',
'pyeditor': 'import pyeditor\n# Opens a new unsaved buffer with an unused filename.\npyeditor.new_file("demo.py")',
'pyfiles': 'import pyfiles\npyfiles.browse("/")',
'pyperm': 'import pyperm\n# Replace demo.py with your file.\nprint(pyperm.get_mode("demo.py"))\nprint(pyperm.readable("demo.py"))',
'pyterm': 'import pyterm\nprint(pyterm.commands())\npyterm.man("python")\nprint(pyterm.startup_view())',
'zipfile': 'import zipfile\n# demo.py must exist; demo.zip and output/demo.py must not exist.\narchive = zipfile.compress("demo.py", "demo.zip")\nprint(zipfile.namelist(archive))\nzipfile.extract(archive, "output")',
}

# Exact qualified entries override shared descriptions below.
DESCRIPTIONS = {
'py3d.vec3': 'Return an (x, y, z) tuple with all three components converted to float. Example: vec3(1, 2, 3) -> (1.0, 2.0, 3.0).',
'py3d.add': 'Return componentwise a + b for two three-component sequences.',
'py3d.sub': 'Return componentwise a - b for two three-component sequences.',
'py3d.scale': 'Multiply all three vector components by amount and return a tuple.',
'py3d.dot': 'Return the scalar sum of corresponding component products.',
'py3d.cross': 'Return the right-handed three-dimensional cross product as a tuple.',
'py3d.normalize': 'Return a unit-length tuple. A zero vector returns (0.0, 0.0, 0.0).',
'py3d.identity': 'Return the row-major 4 x 4 identity transform as 16 numbers.',
'py3d.translation': 'Return a 4 x 4 translation matrix with offsets x, y and z.',
'py3d.scaling': 'Return a 4 x 4 scale matrix. Missing y or z uses x for uniform scaling.',
'py3d.rotation_x': 'Return a 4 x 4 rotation about X; angle is in radians.',
'py3d.rotation_y': 'Return a 4 x 4 rotation about Y; angle is in radians.',
'py3d.rotation_z': 'Return a 4 x 4 rotation about Z; angle is in radians.',
'py3d.focal_length': 'Compute focal length in pixels from viewport width and field of view in degrees.',
'py3d.rgb565': 'Clamp 8-bit RGB channels and pack them as a 16-bit RGB565 integer.',
'py3d.shade_rgb565': 'Scale a packed RGB565 color by a brightness amount and clamp channels.',
'py3d.cube': 'Return (vertices, faces) for a cube centered at the origin with the given side length.',
'py3d.Renderer': 'Create a screen renderer with viewport, projection, background and lighting settings. draw_mesh prepares/draws triangles; present flushes to the LCD.',
'py3d.Renderer.clear': 'Fill the drawing buffer with the renderer background color.',
'py3d.Renderer.present': 'Send the rendered frame to the calculator display.',
'numpy.ndarray': 'Create a flat-backed array with inferred or explicit shape. Ragged nested lists and shape/product mismatches raise ValueError. Use array() for normal construction.',
'numpy.matrix': 'Create a two-dimensional matrix. Supports matrix multiplication and inverse through I/getI().',
'numpy.array': 'Create a new ndarray from a scalar, nested sequence or another array.',
'numpy.asarray': 'Return an existing compatible ndarray or construct one from value.',
'numpy.asmatrix': 'Convert value to a two-dimensional matrix.',
'numpy.zeros': 'Create an array of the requested shape filled with dtype(0).',
'numpy.ones': 'Create an array of the requested shape filled with dtype(1).',
'numpy.full': 'Create an array filled with value, optionally converting each value with dtype.',
'numpy.identity': 'Create an n by n array with ones on the diagonal and zeros elsewhere.',
'numpy.eye': 'Create an n by m array with ones on diagonal k; defaults to a square matrix and main diagonal.',
'numpy.arange': 'Return an array of regularly spaced values, excluding stop. step must be nonzero.',
'numpy.linspace': 'Return num evenly spaced values including both endpoints when num > 1.',
'numpy.concatenate': 'Concatenate input arrays using this compact implementation; see the shape handling below. There is no general axis keyword.',
'numpy.dot': 'Dot product for 1D vectors; higher-dimensional supported cases use matmul.',
'numpy.matmul': 'Multiply compatible vectors/matrices. Inner dimensions must match; see exact supported dimensional cases below.',
'numpy.sqrt': 'Apply square root elementwise to arrays/sequences or directly to a scalar.',
'numpy.sin': 'Apply sine elementwise; input angles are radians.',
'numpy.cos': 'Apply cosine elementwise; input angles are radians.',
'numpy.tan': 'Apply tangent elementwise; input angles are radians.',
'numpy.abs': 'Return elementwise absolute values.',
'numpy.sum': 'Sum all values; there is no general axis parameter.',
'numpy.mean': 'Return the arithmetic mean of all values.',
'numpy.amin': 'Return the smallest flattened value.',
'numpy.amax': 'Return the largest flattened value.',
'numpy.matrix.H': 'Conjugate transpose as implemented by this real-valued subset; see transpose handling below.',
'numpy.matrix.I': 'Return the matrix inverse. Requires square, nonsingular input; failures raise ValueError.',
'numpy.matrix.A': 'Return a copy as ndarray.',
'numpy.matrix.A1': 'Return a flattened one-dimensional ndarray copy.',
'pygame.Color': 'Construct RGB/RGBA components from supported names, packed integers or sequences. Alpha is retained as metadata; general alpha blending is not implemented.',
'pygame.Color.normalize': 'Return RGBA channels divided by 255 as floats.',
'pygame.Rect': 'Create integer rectangle (x, y, width, height), or copy a compatible rectangle/sequence. Right and bottom are exclusive for collisions.',
'pygame.Surface': 'Create an RGB565 offscreen surface. Default allocation is two bytes per pixel. Full-screen offscreen buffers are expensive on the calculator.',
'pygame.Surface.set_alpha': 'Store a global alpha value as metadata. This subset does not apply general per-pixel/global alpha blending during blit.',
'pygame.Surface.get_alpha': 'Return stored alpha metadata; this does not imply blending support.',
'pygame.Surface.get_view': 'Return the backing pixel buffer; kind is accepted for compatibility. This is not the full desktop BufferProxy API.',
'pygame.Surface.lock': 'Compatibility no-op; surfaces do not require explicit locking.',
'pygame.Surface.unlock': 'Compatibility no-op.',
'pygame.Surface.mustlock': 'Return False; locking is not required.',
'pygame.Surface.get_locked': 'Return False; locking is not tracked.',
'pygame.Surface.convert_alpha': 'Return a copy with alpha metadata. No new per-pixel alpha format is allocated.',
'pygame.Surface.subsurface': 'Return a copied rectangular region, not a shared view into the parent surface.',
'pygame.display.set_mode': 'Return the single calculator screen surface. Requested size/window flags are compatibility arguments; physical size remains 396 x 224.',
'pygame.display.update': 'Refresh the screen. Rectangle selection is accepted but does not provide desktop dirty-region window updates.',
'pygame.display.set_icon': 'Compatibility no-op; it does not change the calculator add-in icon.',
'pygame.display.toggle_fullscreen': 'Compatibility result only; the calculator already has one full-screen display.',
'pygame.display.Info': 'Return an object describing the fixed display dimensions and pixel format.',
'pygame.key.set_mods': 'Compatibility no-op; physical key state determines modifiers.',
'pygame.key.set_repeat': 'Store repeat configuration for compatibility; inspect get_repeat. It does not install desktop keyboard repeat handling.',
'pygame.mouse.get_pos': 'Return (0, 0). There is no mouse device.',
'pygame.mouse.get_pressed': 'Return false button states. There is no mouse device.',
'pygame.mouse.set_visible': 'Compatibility result; no system mouse cursor is drawn.',
'pygame.mouse.get_visible': 'Return False; no mouse cursor exists.',
'pygame.Font': 'Use the calculator default font. file and size are compatibility inputs; rendering does not load desktop TTF fonts.',
'pygame.Font.render': 'Return a surface holding text for native gint drawing. antialias and general wraplength behavior are limited; see implementation.',
'pygame.font.SysFont': 'Construct the calculator Font; requested desktop font family is not loaded. Bold/italic are stored flags.',
'pygame.font.match_font': 'Return compatibility font matching information for the single built-in font.',
'pygame.font.get_fonts': 'Return the available compatibility font names; not a system TTF search.',
'pygame.image.get_extended': 'Return False; extended desktop image codecs are unavailable.',
'pygame.image.load': 'Load supported BMP/PPM data. Prepared CG50 BMP loading is limited to 56 x 56; PNG/JPEG are not supported here.',
'pygame.transform.rotate': 'Rotate by an angle in degrees using nearest-pixel sampling into a new bounding surface. The color key is retained and fills exposed corners. This is not an antialiased desktop transform.',
'pygame.transform.rotozoom': 'Apply the supported rotation then scaling. This is not a general antialiased rotozoom implementation.',
'pygame.Sprite': 'Base sprite carrying group membership. Set image and rect on your subclass; override update for game behavior.',
'pygame.Sprite.update': 'Default no-op for subclasses to override.',
'pygame.Group': 'Container for unique sprites with add/remove/update/draw. No automatic background clearing or dirty-rectangle restoration.',
'pygame.Group.draw': 'Blit each sprite.image at sprite.rect and return the resulting rectangles. Clear/redraw the background yourself each frame.',
'pygame.GroupSingle': 'Group holding at most one sprite; adding a new sprite replaces the old member.',
'pygame.RenderPlain': 'Group subclass with ordinary drawing behavior.',
'pygame.get_sdl_version': 'Return a compatibility tuple; no SDL library is running on the calculator.',
'pygame.get_error': 'Return the stored compatibility error string.',
'pygame.set_error': 'Store a compatibility error message.',
'pygame.Clock': 'Track elapsed frame time and optionally cap frame rate. Also exported as pygame.time.Clock.',
'pygame.Event': 'Create an event with numeric type plus attributes from a dictionary and/or keyword arguments.',
'pygame.math.Vector2': 'Create a two-component float vector from components or a sequence. Supports x/y properties, indexing and arithmetic.',
'pygame.math.Vector3': 'Create a three-component float vector from components or a sequence. Supports x/y/z properties, indexing and arithmetic.',
'pythonultra.modules': 'Return Catalog module names as a tuple. This list may be smaller than the full bundled module inventory.',
'pythonultra.catalog_data': 'Return the Catalog member-name tuple for name, or an empty tuple for an unknown module.',
'pythonultra.catalog': 'Print all Catalog modules or one module member list. Returns the selected module tuple when found.',
'pythonultra.menu_border': 'Return the RGB565 RC menu border color; invalid/missing configuration defaults to run130.1 red.',
'pythonultra.symbol_ui': 'Open the punctuation/symbol picker; returns the selected character or None on cancel.',
'pythonultra.catalog_ui': 'Open module/member menus; returns (module, member) or None on cancel.',
'pythonultra.catalog_insert_ui': 'Open Catalog and return insertion text or None; the caller inserts it at its cursor.',
'pythonultra.info_lines': 'Return the build/about information strings.',
'pythonultra.info_ui': 'Display the build/about information menu.',
'pyeditor.Editor': 'Create an editor buffer and attempt to load filename. Call run() to enter the interactive editor.',
'pyfiles.Browser': 'Create a file-browser controller for the requested directory and theme; call run() for the UI.',
'pyfiles.browse': 'Launch the file browser and restore display/font state when it returns.',
'pyterm.commands': 'Return the supported terminal command names.',
'pyterm.man': 'Print usage and description for a terminal command.',
'pyterm.source': 'Read and execute commands from an RC/script file using the terminal command parser.',
'pyterm.config': 'Return the current RC/settings dictionary.',
'pyterm.startup': 'Load terminal startup configuration/history as implemented below.',
'pyterm.history_tail': 'Return the most recent history entries, bounded by the requested count.',
'pyterm.menu_border': 'Parse the configured named/hex color; return default red for missing or invalid input.',
'pyterm.dispatch': 'Interpret one terminal line and return the native shell action code. Use man() for command syntax; native UI actions need the host shell bridge.',
'pyperm.abspath': 'Normalize a path against the current directory and collapse . and .. components.',
'pyperm.reset_cache': 'Drop cached permission data so the next access reloads it.',
'pyperm.is_dir': 'Return whether the path is a directory according to os.stat.',
'pyperm.get_mode': 'Return the virtual permission mode, falling back to default file/directory permissions.',
'pyperm.chmod': 'Set and persist a virtual octal permission mode for the normalized path.',
'pyperm.remove': 'Remove virtual permission records for the path; does not itself delete file contents.',
'pyperm.move': 'Move virtual permission records from old_path to new_path; the filesystem move is a separate operation.',
'pyperm.readable': 'Return whether virtual permissions allow reading.',
'pyperm.writable': 'Return whether virtual permissions allow writing.',
'pyperm.executable': 'Return whether virtual permissions allow execution.',
'pyperm.require_read': 'Raise OSError if the virtual permission check denies reading.',
'pyperm.require_write': 'Raise OSError if the virtual permission check denies writing.',
'pyperm.require_execute': 'Raise OSError if the virtual permission check denies execution.',
'pyperm.format_mode': 'Return a human-readable virtual permission representation.',
}

# Shared operations; module-specific entries above take precedence.
DESCRIPTIONS.update({
'copy':'Return an independent copy of this object or container.',
'update':'Replace the object values or update its members using the arguments shown. See the implementation for the container-specific behavior.',
'length':'Return Euclidean vector length.', 'length_squared':'Return the sum of squared vector components without a square root.',
'dot':'Return the vector dot product; component counts must match.',
'cross':'Return a cross product: Vector2 returns a scalar; Vector3 returns a vector.',
'normalize':'Return a unit-length copy; see zero-length behavior in the implementation.',
'normalize_ip':'Normalize this vector in place; zero length raises ValueError.',
'is_normalized':'Test whether squared length is approximately one.',
'scale_to_length':'Scale the vector in place to the requested length.',
'distance_squared_to':'Return squared Euclidean distance to another vector.',
'distance_to':'Return Euclidean distance to another vector.',
'lerp':'Return linear interpolation toward the other value by the supplied amount.',
'angle_to':'Return the signed angle in degrees to another Vector2.',
'rotate':'Return a Vector2 rotated by an angle in degrees.',
'rotate_ip':'Rotate this Vector2 in place, in degrees.',
'x':'Read/write the horizontal component.', 'y':'Read/write the vertical component.', 'z':'Read/write the depth component.',
'width':'Read/write rectangle width.', 'height':'Read/write rectangle height.',
'left':'Read/write the left edge; assigning moves the rectangle.', 'right':'Read/write the exclusive right edge; assigning moves the rectangle.',
'top':'Read/write the top edge; assigning moves the rectangle.', 'bottom':'Read/write the exclusive bottom edge; assigning moves the rectangle.',
'centerx':'Read/write the horizontal center.', 'centery':'Read/write the vertical center.',
'center':'Read/write the (x, y) center tuple.', 'size':'Read the object size (array element count or width/height pair; see implementation).',
'topleft':'Read/write the top-left coordinate pair.', 'topright':'Read/write the top-right coordinate pair.',
'bottomleft':'Read/write the bottom-left coordinate pair.', 'bottomright':'Read/write the bottom-right coordinate pair.',
'midtop':'Read/write the top-edge midpoint.', 'midbottom':'Read/write the bottom-edge midpoint.',
'midleft':'Read/write the left-edge midpoint.', 'midright':'Read/write the right-edge midpoint.',
'move':'Return a translated rectangle, or move an editor cursor by dy/dx; see the exact signature and implementation.',
'move_ip':'Translate this rectangle in place.', 'inflate':'Return a rectangle resized around its center.', 'inflate_ip':'Resize this rectangle around its center in place.',
'clamp':'Return a copy repositioned inside another rectangle.', 'clamp_ip':'Reposition this rectangle inside another rectangle.',
'clip':'Return rectangle intersection; no overlap gives an empty rectangle.',
'union':'Return the smallest rectangle containing both rectangles.', 'union_ip':'Expand this rectangle to contain the other rectangle.',
'unionall':'Return a rectangle covering this rectangle and every supplied rectangle.',
'contains':'Return whether this rectangle fully contains another.',
'collidepoint':'Test a point against the rectangle; right/bottom edges are excluded.',
'colliderect':'Test whether rectangles overlap with positive area.',
'collidelist':'Return index of the first colliding rectangle, or -1.',
'collidelistall':'Return indexes of all colliding rectangles.',
'correct_gamma':'Return a Color with gamma-adjusted channels.',
'get_size':'Return (width, height).', 'get_width':'Return width in pixels.', 'get_height':'Return height in pixels.',
'get_rect':'Return a bounding Rect; keyword attributes can position it.',
'get_flags':'Return stored surface flags.', 'get_bitsize':'Return 16 for RGB565 pixels.',
'get_bytesize':'Return 2 bytes per RGB565 pixel.', 'get_pitch':'Return row stride in bytes.',
'get_buffer':'Return the backing writable pixel buffer when available.',
'set_colorkey':'Set a transparent color or None to disable it. RGB colors are quantized to RGB565 before comparison.',
'get_colorkey':'Return the configured transparent color or None.',
'set_clip':'Set the drawing clip rectangle; None restores the surface bounds.',
'get_clip':'Return a copy of the current drawing clip rectangle.',
'map_rgb':'Convert an RGB color to packed RGB565.', 'unmap_rgb':'Convert RGB565 to a Color.',
'set_at':'Set one pixel, subject to bounds/clip handling.', 'get_at':'Return the pixel Color at the requested coordinate.',
'fill':'Fill the surface or a rectangle with a color; return the affected Rect.',
'blit':'Copy a source Surface at dest, optionally selecting area. Color-key pixels are skipped. Return the affected rectangle.',
'blits':'Apply a sequence of blits; optionally return affected rectangles.',
'convert':'Return a copy in the supported RGB565 representation.',
'scroll':'Move existing surface pixels by dx/dy using the implementation below; repaint newly exposed areas.',
'init':'Initialize this compatibility subsystem.', 'quit':'Release/deactivate this compatibility subsystem.', 'get_init':'Return whether the subsystem was initialized.',
'get_surface':'Return the current display Surface or None.', 'flip':'Present the current frame, or flip a surface along specified axes; see signature.',
'set_caption':'Store the window caption as metadata; calculator OS title bars do not become desktop windows.',
'get_caption':'Return stored caption metadata.', 'get_driver':'Return the calculator display backend name.',
'get_window_size':'Return the fixed calculator display dimensions.', 'list_modes':'Return the supported display modes.',
'mode_ok':'Return the supported bit depth for an accepted mode, or the implementation compatibility result.',
'line':'Draw a line on a Surface; width is in pixels.',
'lines':'Draw connected line segments; closed joins the last point to the first.',
'rect':'Draw a filled rectangle for width=0 or an outline otherwise. Rounded-corner arguments are compatibility inputs.',
'circle':'Draw a filled circle or outline. See the implementation for quadrant-argument limitations.',
'ellipse':'Draw a filled ellipse or outline within a bounding Rect.',
'polygon':'Draw a filled polygon or closed outline from vertices.',
'arc':'Approximate an arc with line segments; angles are radians.',
'tick':'Return elapsed milliseconds; framerate > 0 inserts a delay to cap frame rate.',
'get_time':'Return milliseconds from the most recent tick including frame limiting.',
'get_rawtime':'Return milliseconds from the most recent tick excluding frame-limit delay.',
'get_fps':'Return the clock estimate of frames per second.',
'get_ticks':'Return elapsed milliseconds since initialization.',
'delay':'Pause for milliseconds and return measured elapsed milliseconds.',
'get_pressed':'Return a key-state object indexed by Pygame key constants.',
'get_mods':'Return current SHIFT/ALPHA modifier flags.', 'name':'Return a readable name for a key code.',
'get_repeat':'Return the stored repeat delay/interval pair.',
'pump':'Process pending hardware events into the compatibility event queue.',
'post':'Append a software-created Event to the queue.',
'get':'Return and remove queued events, with optional type filtering/exclusion.',
'poll':'Return the next queued event or a NOEVENT event.',
'wait':'Wait for an event, optionally with a millisecond timeout.',
'clear':'Clear queued events, optionally by type; renderer clear methods instead clear the drawing buffer.',
'peek':'Test whether events of the selected type are queued without removing them.',
'custom_type':'Allocate the next user event type number.', 'event_name':'Return a readable name for an event type.',
'get_linesize':'Return the line spacing in pixels.', 'get_ascent':'Return the font ascent.', 'get_descent':'Return the font descent.',
'set_bold':'Store the font bold flag; the fixed native glyphs are not synthesized into a new TTF face.', 'get_bold':'Return the stored bold flag.',
'set_italic':'Store the font italic flag.', 'get_italic':'Return the stored italic flag.',
'set_underline':'Store the font underline flag.', 'get_underline':'Return the stored underline flag.',
'get_default_font':'Return the default calculator font identifier.',
'frombuffer':'Create a Surface from packed RGB data; this implementation may copy rather than share the buffer.',
'fromstring':'Decode supported packed RGB/RGBA pixel data into a Surface; optional flipped reverses rows.',
'tostring':'Encode surface pixels as the requested supported RGB/RGBA byte sequence.',
'from_gint':'Wrap a native gint image as a Surface.',
'scale':'Resize by nearest-neighbor sampling, optionally into dest_surface.',
'scale_by':'Resize using a scalar or x/y factor.',
'add':'Add sprites/groups to membership without duplicate entries.',
'remove':'Remove sprites/groups from membership.', 'kill':'Remove the sprite from all groups.',
'alive':'Return whether this sprite belongs to any group.', 'groups':'Return a list of groups containing this sprite.',
'sprites':'Return a list of group members.', 'has':'Test whether all supplied sprites are members.',
'empty':'Remove every sprite from the group.', 'sprite':'Read/write the single member; None empties the group.',
'collide_rect':'Test sprites using their rect attributes.',
'collide_rect_ratio':'Return a collision callback using scaled rectangle bounds.',
'spritecollide':'Return sprites colliding with sprite. If dokill, remove matches from all groups; optional callback replaces rectangle collision.',
'spritecollideany':'Return the first colliding sprite or None.',
'groupcollide':'Return a dictionary mapping colliding groupa sprites to matching groupb sprites; kill flags remove matched sprites from groups.',
'ndim':'Return the number of array dimensions.', 'tolist':'Return nested Python lists matching the shape.',
'flatten':'Return a one-dimensional copy.', 'reshape':'Return a copy with a compatible new shape; element count must match.',
'astype':'Return a copy with each element converted using dtype.', 'sum':'Return the sum of all elements.',
'mean':'Return the mean of all elements.', 'min':'Return the smallest element.', 'max':'Return the largest element.',
'T':'Return the transpose.', 'transpose':'Swap the supported array/matrix axes; see dimensional handling.',
'getA':'Return the matrix as an ndarray copy.', 'getA1':'Return a flattened ndarray copy.',
'getT':'Return the transpose.', 'getH':'Return H (the supported conjugate-transpose operation).',
'getI':'Return the matrix inverse; requires a square nonsingular matrix.',
'themes':'Return available editor theme names.', 'set_theme':'Select a named syntax/UI palette.',
'apply_font':'Apply a supported system font size and recompute visible rows/columns.',
'resolve_char':'Translate a physical key using editor numeric/alpha/shift state.',
'draw_line':'Render one editor line with syntax coloring and cursor/selection handling.',
'draw':'Render the controller or group contents; see signature and implementation.',
'popup':'Display a modal choice list; returns a selected value or None on cancel.',
'input_bar':'Prompt for text; returns text or None on cancel.',
'insert':'Insert text at the cursor, including multiline paste, subject to editor size limits.',
'backspace':'Delete before the cursor or merge with the previous line.',
'newline':'Split the current line and apply leading-space/colon indentation.',
'copy_selection':'Copy the selected text; cut=True also removes it from the buffer.',
'find':'Prompt for a search string and move to the next match, wrapping once.',
'style_menu':'Open editor syntax-theme/font options.', 'catalog_menu':'Open Catalog and insert the qualified selection at the cursor.',
'confirm_discard':'Ask before discarding dirty contents; return True only when discard is allowed.',
'run':'Enter the interactive controller event loop; returns when the user exits or requests a native action.',
'refresh':'Reload directory entries, sorting and preserving a valid selected index.',
'selected_entry':'Return the highlighted directory entry or None.', 'selected_path':'Return the highlighted absolute path or None.',
'selection_targets':'Return the selected/marked paths for file actions.',
'draw_softkeys':'Draw the six function-key labels.', 'toggle_selected':'Toggle the marked state of the highlighted entry.',
'sequence_menu':'Choose file sorting/order options.', 'search_menu':'Search filenames and select a match.',
'text_viewer':'Open a read-only text preview. Current long-line clipping is tracked as a hardware usability defect.',
'checksum_ui':'Compute and display the selected file digest.', 'file_info':'Display file metadata and related actions.',
'enter_selected':'Enter a directory or invoke the selected file action.',
'run_file':'Run a Python source file with permission checks.', 'edit_file':'Open the selected text file in the editor.',
'open_editor':'Launch the editor through the browser handoff.', 'create_new':'Prompt for a new file/folder name and create it.',
'rename_selected':'Prompt for a new name and rename the selected entry.',
'delete_selected':'Confirm and delete selected targets.',
'set_clipboard':'Store selected paths for copy or cut.', 'paste_clipboard':'Copy/move clipboard targets into the current folder.',
'clipboard_menu':'Display clipboard/multiselection actions.', 'permission_menu':'Display and change virtual permission bits.',
'compress_selected':'Create a ZIP from selected paths and report the result.',
'extract_selected':'Extract the highlighted archive with file-safety checks.',
'more_menu':'Display secondary browser actions.',
})

NATIVE = {}

def native(module, rows):
    for signature, detail in rows:
        NATIVE[module + '.' + signature.split('(')[0]] = (signature, detail)

native('builtins', [
('abs(x)', 'Return the absolute value of a number.'),
('all(iterable)', 'True if every item is truthy; True for an empty iterable.'),
('any(iterable)', 'True if at least one item is truthy; False for an empty iterable.'),
('bin(x)', 'Return the integer in binary with a 0b prefix.'),
('bool(x=False)', 'Convert using Python truth testing.'),
('bytearray(source=0)', 'Create a mutable byte buffer from a length or byte iterable. Each element is 0..255.'),
('bytes(source=b"", encoding=None)', 'Create immutable bytes. For text, supply an encoding; a length creates zero bytes.'),
('callable(obj)', 'Test whether an object supports calls.'),
('chr(code)', 'Return the character for a Unicode code point.'),
('classmethod(function)', 'Decorator binding a method to its class instead of an instance.'),
('complex(real=0, imag=0)', 'Construct a complex number; real and imag attributes expose its components.'),
('dict(iterable=(), **kwargs)', 'Create a dictionary from pairs or a mapping; keyword arguments add entries.'),
('dir(obj)', 'Return accessible attribute names. The no-argument form lists the local scope.'),
('divmod(a, b)', 'Return (a // b, a % b).'),
('enumerate(iterable, start=0)', 'Iterate (index, item) pairs.'),
('eval(source, globals=None, locals=None)', 'Evaluate a Python expression and return its result. Use only code you intend to execute.'),
('exec(source, globals=None, locals=None)', 'Execute Python statements; return None.'),
('filter(function, iterable)', 'Iterate items for which function is true; None tests item truth directly.'),
('float(x=0)', 'Convert a number or numeric string to floating point.'),
('frozenset(iterable=())', 'Create an immutable set of unique hashable elements.'),
('getattr(obj, name, default)', 'Get a named attribute. default is optional; without it a missing attribute raises AttributeError.'),
('globals()', 'Return the current global namespace dictionary.'),
('hasattr(obj, name)', 'Test whether the named attribute can be accessed.'),
('hash(obj)', 'Return a hash for a hashable object.'),
('help(obj)', 'Print the current MicroPython object/member help. No argument prints startup help; help("modules") lists imports. Rich function documentation is still pending in this build.'),
('hex(x)', 'Return the integer in hexadecimal with a 0x prefix.'),
('id(obj)', 'Return object identity; do not interpret it as a supported arbitrary memory pointer.'),
('input(prompt="")', 'Display a prompt and read a line from the interactive shell.'),
('int(x=0, base=10)', 'Convert to an integer. base applies when x is a string/bytes representation.'),
('isinstance(obj, types)', 'Test whether obj is an instance of a type or tuple of types.'),
('issubclass(cls, types)', 'Test class inheritance against a type or tuple of types.'),
('iter(iterable)', 'Return an iterator for the object.'),
('len(obj)', 'Return number of elements/characters.'),
('list(iterable=())', 'Create a mutable list.'),
('locals()', 'Return the local namespace as exposed by MicroPython; function-local introspection is limited.'),
('map(function, *iterables)', 'Iterate function applied to corresponding items, stopping with the shortest iterable.'),
('max(iterable, *, key=None)', 'Return the largest item; also supports max(a, b, ...). Empty input without a supported default raises ValueError.'),
('min(iterable, *, key=None)', 'Return the smallest item; also supports min(a, b, ...).'),
('next(iterator, default)', 'Return the next item. default is optional; otherwise exhaustion raises StopIteration.'),
('object()', 'Create a basic object; base class for ordinary classes.'),
('oct(x)', 'Return the integer in octal with a 0o prefix.'),
('open(path, mode="r")', 'Open a calculator file. Modes r/w/a plus b or t and supported + select access. w truncates existing content. Use with or close(); seek/tell/flush are provided by the native file object.'),
('ord(character)', 'Return the Unicode code point of one character.'),
('pow(base, exponent, modulus)', 'Return exponentiation; modulus is optional and selects modular integer exponentiation.'),
('print(*objects, sep=" ", end="\\n")', 'Write objects to the shell with a separator and ending. This port does not enable general sys standard-file redirection.'),
('property(fget=None, fset=None, fdel=None, doc=None)', 'Create a managed attribute; use @property and @name.setter on class methods. Optional behavior follows MicroPython.'),
('range(start, stop, step=1)', 'Iterate integer values excluding stop. range(stop) starts at zero; step cannot be zero.'),
('repr(obj)', 'Return a printable representation useful for debugging.'),
('reversed(sequence)', 'Iterate a sequence in reverse order.'),
('round(number, ndigits=0)', 'Round a number; integer ndigits handling is enabled in this port.'),
('set(iterable=())', 'Create a mutable set of unique hashable elements.'),
('setattr(obj, name, value)', 'Assign a named attribute when the object type supports assignment.'),
('sorted(iterable, key=None, reverse=False)', 'Return a sorted list; key and reverse are keyword arguments.'),
('staticmethod(function)', 'Decorator for a method that does not receive self or cls automatically.'),
('str(obj="")', 'Convert to text; decoding bytes accepts encoding/error arguments as supported by MicroPython.'),
('sum(iterable, start=0)', 'Add all items to start and return the total.'),
('super(type, obj)', 'Access inherited methods; zero-argument super() is available in normal methods.'),
('tuple(iterable=())', 'Create an immutable sequence.'),
('type(obj)', 'Return the object type; type(name, bases, namespace) constructs a class.'),
('zip(*iterables)', 'Iterate tuples of corresponding items, stopping at the shortest input.'),
('GeneratorExit(*args)', 'Raised when a generator is closed.'),
('StopIteration(*args)', 'Signals iterator exhaustion; next(iterator, default) can supply a fallback.'),
('StopAsyncIteration(*args)', 'Signals async iterator exhaustion where asynchronous iteration is supported.'),
])
native('ctypes', [
('c_int(value)', 'Convert to a Python integer; there is no .value wrapper.'),
('c_uint(value)', 'Convert to a nonnegative Python integer; negative input raises ValueError.'),
('c_float(value)', 'Convert to a Python float; target Python floats are double precision.'),
('c_double(value)', 'Alias of c_float in this restricted interface.'),
('c_bool(value)', 'Convert using Python truth testing.'),
('buffer(size)', 'Create a managed bytearray of size zero-initialized bytes.'),
('read_u8(buffer, offset)', 'Read one byte; offsets outside the buffer raise ValueError.'),
('write_u8(buffer, offset, value)', 'Write a byte 0..255 to a writable buffer with bounds checking.'),
('fill(buffer, value)', 'Fill a writable buffer with byte value 0..255; return the buffer.'),
('copy(destination, destination_offset, source, source_offset, count)', 'Copy bytes with overlap-safe semantics. Bounds/negative count checks raise ValueError; return destination.'),
('available()', 'Return allowed native call names: abs, sqrt, sin, cos, pow, clamp.'),
('call(name, *args)', 'Call an allowlisted operation: abs(x), sqrt(x), sin(x), cos(x), pow(x,y), clamp(x,lo,hi). Unknown names or wrong argument counts raise ValueError.'),
('SAFE', 'True: this module exposes only managed buffers and allowlisted calls.'),
])
native('gint', [
('dsubimage_colorkey(x, y, image, left, top, width, height, key)', 'Draw a rectangular RGB565 image region while skipping pixels equal to the RGB565 key. Source and screen/window bounds are clipped. Uses current image-buffer contents, allocates no image copy, and does not refresh the LCD; call dupdate/pygame.display.flip after completing the frame. Other image formats raise ValueError.'),
('C_RGB(r, g, b)', 'Pack RGB channels expressed in the native 0..31 range. For 8-bit RGB use a conversion such as ((r>>3)<<11)|((g>>2)<<5)|(b>>3).'),
('dclear(color)', 'Fill the entire drawing buffer with an RGB565 color.'),
('dupdate()', 'Present the drawing buffer on the LCD.'),
('drect(x1, y1, x2, y2, color)', 'Fill a rectangle with inclusive corner coordinates.'),
('drect_border(x1, y1, x2, y2, fill_color, border_width, border_color)', 'Draw a filled rectangle and a border of the requested pixel thickness.'),
('dpixel(x, y, color)', 'Set a clipped pixel in the drawing buffer.'),
('dgetpixel(x, y)', 'Read a drawing-buffer RGB565 pixel; keep coordinates inside the screen.'),
('dline(x1, y1, x2, y2, color)', 'Draw a line between inclusive endpoints.'),
('dtriangle(x1, y1, x2, y2, x3, y3, color)', 'Rasterize a filled triangle with clipping.'),
('dhline(y, color)', 'Draw a horizontal line across the active drawing region.'),
('dvline(x, color)', 'Draw a vertical line across the active drawing region.'),
('dcircle(x, y, radius, fill, border)', 'Draw a circle with separate fill and border colors; C_NONE suppresses a component.'),
('dellipse(x1, y1, x2, y2, fill, border)', 'Draw an ellipse inside corner coordinates with separate fill/border colors.'),
('dpoly(coordinates, fill, border)', 'Draw a polygon from a flat Python list [x0,y0,x1,y1,...], with fill and border colors.'),
('dtext(x, y, color, text)', 'Draw text at the given position using the active font.'),
('dtext_opt(x, y, foreground, background, halign, valign, text, size)', 'Draw aligned text with optional background; size limits bytes (-1 for the full string). Use DTEXT_* constants.'),
('dsize(text)', 'Return (pixel_width, pixel_height) in the active font. Width excludes the final inter-glyph gap.'),
('dfont(font)', 'Set a native font; None restores the default. Returns None in this Python wrapper.'),
('dfont_builtin(name)', 'Select small, normal or large (plus prepared jb choices if present). Returns (fallback_width, line_height). Editor uses measured dsize for actual widths.'),
('pollevent()', 'Return the next physical event without blocking; type=KEYEV_NONE means the queue is empty. Processing events updates key state.'),
('clearevents()', 'Drain pending events while updating state; this deliberately discards queued presses/releases.'),
('cleareventflips()', 'Clear recorded press/release transition flags without discarding held state.'),
('keydown(key)', 'Return whether a physical gint key is currently down according to processed state.'),
('keydown_all(*keys)', 'True if every supplied physical key is down.'),
('keydown_any(*keys)', 'True if at least one supplied physical key is down.'),
('keypressed(key)', 'Test whether the key has a recorded press transition.'),
('keyreleased(key)', 'Test whether the key has a recorded release transition.'),
('getkey()', 'Block for an accepted key event using normal modifier/repeat/menu processing.'),
('getkey_opt(options, timeout)', 'Block with GETKEY_* option flags and a timeout in milliseconds; inspect the returned event type for timeout.'),
('keycode_function(key)', 'Return the function-key number corresponding to a physical key, or the native non-function result.'),
('keycode_digit(key)', 'Return the numeric digit corresponding to a physical key, or the native non-digit result.'),
('image(format, color_count, width, height, stride, data, palette=None)', 'Build a native image wrapper over buffers. stride is bytes per row. Keep buffers alive; use convenience constructors for normal RGB565 images.'),
('font(prop, line_height, data_height, block_count, glyph_count, char_spacing, line_distance, blocks, data, width, storage_size, glyph_index, glyph_width, name="")', 'Advanced native bitmap-font constructor; metadata/buffer layout must match gint. Prefer dfont_builtin for calculator system fonts.'),
('image_rgb565(width, height, data)', 'Wrap packed native-endian RGB565 pixels, two bytes per pixel. A writable bytearray is recommended.'),
('image_rgb565a(width, height, data)', 'Wrap gint RGB565A pixels with its format-specific transparent sentinel; this is not RGBA or an arbitrary color-key parameter.'),
('image_p8_rgb565(width, height, data, palette)', 'Wrap 8-bit indexed pixels and a packed RGB565 palette using the gint P8 layout.'),
('image_p8_rgb565a(width, height, data, palette)', 'P8 indexed image with gint transparent-index semantics.'),
('image_p4_rgb565(width, height, data, palette)', 'Wrap 4-bit indexed pixels, two per byte, and a 16-color packed RGB565 palette.'),
('image_p4_rgb565a(width, height, data, palette)', 'P4 indexed image with gint transparent-index semantics.'),
('dimage(x, y, image)', 'Draw a native image at the destination position.'),
('dsubimage(x, y, image, left, top, width, height)', 'Draw the requested source-image rectangle at the destination; no extra flags argument in this wrapper.'),
])
native('casioplot', [
('clear_screen()', 'Clear the buffer to white.'),
('show_screen()', 'Present graphics on the calculator display.'),
('set_pixel(x, y, color=(0,0,0))', 'Set a pixel using an 8-bit RGB tuple.'),
('get_pixel(x, y)', 'Read a pixel as an RGB tuple; out-of-screen input returns None.'),
('draw_string(x, y, text, color=(0,0,0), size="medium")', 'Draw text with a Casio-style small/medium/large size; the native font determines metrics.'),
])
native('kandinsky', [
('color(r, g, b)', 'Pack three 8-bit RGB channels into the native color integer.'),
('set_pixel(x, y, color)', 'Set a pixel using an integer, supported color name or RGB tuple.'),
('get_pixel(x, y)', 'Read the pixel as an RGB tuple (quantized to RGB565 channels).'),
('fill_rect(x, y, width, height, color)', 'Draw a filled rectangle; dimensions differ from gint corner-coordinate drect.'),
('draw_string(text, x, y, color="black", background=None)', 'Draw NumWorks-style text; newline is supported. Omitted background is transparent.'),
('CGEXT_Enable_Wide_Screen()', 'Disable the centered 320 x 222 clipping window.'),
('CGEXT_Disable_Wide_Screen()', 'Restore the centered NumWorks-sized clipping window.'),
('CGEXT_Is_Wide_Screen_Enabled()', 'Current implementation returns is_dwindowed, so True actually means windowed mode. This name/result mismatch is a known limitation.'),
('CGEXT_Set_Margin_Color(color)', 'Clear the whole screen to color and return the windowed-mode flag; it does more than recolor margins.'),
])
native('ion', [
('keydown(key)', 'Return whether a translated NumWorks-style key is pressed. Internally clears pending gint events; avoid mixing event consumers.'),
('battery()', 'Return measured main-battery voltage in volts.'),
('battery_level()', 'Return a coarse level 0..3 based on voltage thresholds (3.6, 3.7, 3.8 V).'),
('battery_charging()', 'Always False for this calculator compatibility implementation.'),
('get_keys()', 'Return a set of pressed mapped key names; drains gint events.'),
('set_brightness(level)', 'Clamp level to 0..240 and write the display-controller brightness register. This path needs verification on newer display hardware.'),
('get_brightness()', 'Read the display-controller register. It includes the native offset and may not round-trip the set_brightness input exactly.'),
])
native('checksum', [('sha256_file(path)', 'Return the lowercase hexadecimal SHA-256 digest of a readable file.'), ('sha1_file(path)', 'Return the lowercase hexadecimal SHA-1 digest of a readable file.')])
native('os', [('sep', 'The path separator string: /.'), ('unlink(path)', 'Alias of remove(path); delete a file, not a directory.'), ('stat(path)', 'Return (mode, ino, dev, nlink, uid, gid, size, atime, mtime, ctime). Some native fields are unavailable; do not interpret absent/invalid timestamp values as real dates.')])
native('time', [('time()', 'Return RTC ticks / 128, currently seconds since midnight. This is not Unix epoch time; date setting is not implemented.'), ('time_ns()', 'Native nanosecond time hook; wall-clock semantics remain incomplete in this port. Do not use as a trustworthy file timestamp.'), ('monotonic()', 'Current implementation returns clock()*1e9/CLOCKS_PER_SEC as a float (nanosecond-valued units, not standard seconds). Use ticks_ms/ticks_diff for ordinary elapsed timing.')])
native('gc', [('isenabled()', 'Return whether automatic garbage collection is enabled.')])
native('micropython', [('heap_lock()', 'Prevent heap allocations; nested locks require matching unlocks. Allocation while locked raises MemoryError.'), ('heap_unlock()', 'Release one heap lock and return remaining lock depth. Always unlock in finally.')])
NATIVE['io.open'] = NATIVE['builtins.open']
DESCRIPTIONS.update({
'numpy.norm': 'Return Euclidean length of a vector (square root of sum of squares).',
'py3d.transform': 'Apply a row-major 4 x 4 matrix to a vertex; divide by homogeneous w when w is neither zero nor one.',
'py3d.Renderer.draw_mesh': 'Prepare transformed/projected triangles, optionally cull/light/sort, and draw them using gint. Returns the prepared triangle count.',
'pyeditor.Editor.start_new': 'Start a new unsaved buffer; refuse to overwrite an existing filename.',
'pyeditor.Editor.save_file': 'Save via a temporary sibling with rollback backup. Return success; on error preserve the buffer and report a message.',
'pygame.error': 'Pygame-compatible exception class derived from Exception.',
'zipfile.namelist': 'Read the archive directory and return stored entry names.',
})
EXAMPLES['binascii'] = 'import binascii\nprint(binascii.b2a_base64(b"AB"))\nprint(binascii.crc32(b"hello"))'

# Native object methods; signatures omit the bound receiver.
METHODS = {}
for signature, detail in [
('append(value)', 'Append one element to the mutable sequence.'),
('extend(iterable)', 'Append all elements from the iterable.'),
('clear()', 'Remove all entries in place.'),
('copy()', 'Return a shallow independent copy.'),
('count(value)', 'Count matching elements or non-overlapping substring occurrences.'),
('index(value, start=0, stop=None)', 'Return the first matching position; raise ValueError when absent. Omit stop to search the remainder.'),
('insert(index, value)', 'Insert value before the selected list position.'),
('pop(index=-1)', 'Remove and return an element; for a list, default removes the last element.'),
('remove(value)', 'Remove a matching element; absent values raise the container-specific error.'),
('reverse()', 'Reverse list elements in place.'),
('sort(key=None, reverse=False)', 'Sort the list in place; key and reverse are keyword arguments.'),
('fromkeys(iterable, value=None)', 'Construct a dictionary with each iterable item as a key and the same value object.'),
('get(key, default=None)', 'Return a dictionary value or default without raising KeyError.'),
('items()', 'Return an iterable view of (key, value) entries.'),
('keys()', 'Return an iterable view of keys.'),
('values()', 'Return an iterable view of values.'),
('popitem()', 'Remove and return a dictionary (key, value) pair; ordering is not a portable guarantee.'),
('setdefault(key, default=None)', 'Return the value if present; otherwise insert and return default.'),
('update(other=(), **kwargs)', 'Merge mapping/iterable pairs into the dictionary; supplied entries replace existing values.'),
('add(value)', 'Add a hashable element to the set.'),
('discard(value)', 'Remove a set element if present; absence is harmless.'),
('difference(*others)', 'Return elements present here but not in the other collections.'),
('difference_update(*others)', 'Remove elements found in other collections, in place.'),
('intersection(*others)', 'Return elements common to all supplied collections.'),
('intersection_update(*others)', 'Keep only elements common to all collections, in place.'),
('isdisjoint(other)', 'True when the two sets have no common elements.'),
('issubset(other)', 'True when every element here also occurs in other.'),
('issuperset(other)', 'True when this set contains every element in other.'),
('symmetric_difference(other)', 'Return elements found in exactly one of the two sets.'),
('symmetric_difference_update(other)', 'Replace this set with its symmetric difference.'),
('union(*others)', 'Return all distinct elements from these collections.'),
('find(sub, start=0, end=None)', 'Return the first substring position or -1; omit end to search the remainder.'),
('rfind(sub, start=0, end=None)', 'Return the last substring position or -1.'),
('rindex(sub, start=0, end=None)', 'Return the last substring position; raise ValueError when absent.'),
('join(iterable)', 'Concatenate matching text/byte objects using this object as the separator.'),
('split(sep=None, maxsplit=-1)', 'Split into a list; omitted separator splits whitespace.'),
('rsplit(sep=None, maxsplit=-1)', 'Split from the right, subject to maxsplit.'),
('splitlines(keepends=False)', 'Split at line boundaries; optionally retain line endings.'),
('startswith(prefix, start=0, end=None)', 'Test for the prefix in the selected range.'),
('endswith(suffix, start=0, end=None)', 'Test for the suffix in the selected range.'),
('strip(chars=None)', 'Return a copy with matching edge characters removed; default removes whitespace.'),
('lstrip(chars=None)', 'Remove matching characters from the left edge.'),
('rstrip(chars=None)', 'Remove matching characters from the right edge.'),
('format(*args, **kwargs)', 'Replace brace fields using supplied arguments. MicroPython formatting is a subset of desktop formatting.'),
('replace(old, new, count=-1)', 'Return a copy with up to count occurrences replaced; negative count means all.'),
('partition(separator)', 'Return (before, separator, after) at the first match; absent separator gives (self, empty, empty).'),
('rpartition(separator)', 'Partition at the last separator occurrence.'),
('center(width, fillchar=" ")', 'Pad on both sides to the requested width.'),
('lower()', 'Return a lowercase copy; Unicode case mappings may be limited.'),
('upper()', 'Return an uppercase copy; Unicode case mappings may be limited.'),
('isspace()', 'True for nonempty text/bytes containing only recognized whitespace.'),
('isalpha()', 'True for nonempty text/bytes containing only recognized alphabetic characters.'),
('isdigit()', 'True for nonempty text/bytes containing only recognized digit characters.'),
('isupper()', 'Test uppercase character classification.'),
('islower()', 'Test lowercase character classification.'),
('encode(encoding="utf-8", errors="strict")', 'Encode text as bytes using the supported encoding.'),
('decode(encoding="utf-8", errors="strict")', 'Decode bytes as text using the supported encoding.'),
('hex()', 'Return hexadecimal text for the byte contents.'),
('fromhex(text)', 'Construct bytes from hexadecimal text.'),
('read(size=-1)', 'Read up to size bytes/characters; negative size reads to EOF. Reading entire files consumes heap.'),
('readinto(buffer)', 'Read into a writable buffer and return the number of bytes read.'),
('readline(size=-1)', 'Read through a newline or EOF, optionally bounded by size.'),
('readlines()', 'Read remaining lines into a list; potentially large memory allocation.'),
('write(data)', 'Write matching text/binary data and return the number written; I/O failures raise OSError.'),
('seek(offset, whence=0)', 'Move position: 0 from start, 1 relative to current, 2 relative to end, where supported. Return position in normal seekable streams.'),
('tell()', 'Return the current stream position.'),
('flush()', 'Flush pending output; native calculator files are currently unbuffered.'),
('close()', 'Close the stream. DeflateIO finishes compression and closes its wrapped stream only when constructed with close=True.'),
('getvalue()', 'Return the complete in-memory stream contents.'),
('truncate(size=None)', 'Resize the in-memory stream, defaulting to its current position.'),
('fileno()', 'Return the underlying native file descriptor.'),
('readinto1(buffer)', 'Read into a writable buffer using the stream implementation.'),
]:
    METHODS[signature.split('(')[0]] = (signature, detail)
METHODS['dict.pop'] = ('pop(key, default)', 'Remove and return a dictionary entry; default is optional, otherwise a missing key raises KeyError.')
METHODS['set.pop'] = ('pop()', 'Remove and return an arbitrary set member; empty set raises KeyError.')
METHODS['set.update'] = ('update(*others)', 'Add all elements from other iterables to this set in place.')
